localenv: "true"
envvalue: kmsenryp  
deploymentBucket: deploymentbucket
region: us-east-1
lambdaIamRole: arn:aws:iam::093584548873:role/lambda_dynamo
environment_tag: "Development"
disabledInfoLogging: "true"
restApiId: ylv4zuzgvj
restApiRootResourceId: rdxzac
vpc_subnet_ids:
  - subnet-xyz
vpc_securitygroup_ids:
  - sg-xyz
kmskeyarn: arn:aws:kms:us-east-1:735723053299:key/1234-234-1234-1234-123456789123