version: 0.2

phases:
  install:
      commands:
        - ls
        - npm install -g serverless
  build:
    commands:
        - npm install --only=dev
  post_build:
    commands:
        - serverless deploy --stage stg --package 3514-PESH-SPF-sls-pkg-stg --force
